# Generated by Django 6.1.1 on 2026-09-13 19:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('service_type', models.CharField(choices=[('sunday_service', 'Sunday Service'), ('midweek_service', 'Midweek Service'), ('bible_study', 'Bible Study'), ('youth_meeting', 'Youth Meeting'), ('womens_ministry', "Women's Ministry"), ('mens_ministry', "Men's Ministry"), ('childrens_ministry', "Children's Ministry"), ('special_event', 'Special Event'), ('other', 'Other Activity')], default='sunday_service', max_length=30)),
                ('session_date', models.DateField(db_index=True, default=datetime.date.today)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.ministry')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=True)),
                ('is_visitor', models.BooleanField(default=False)),
                ('visitor_name', models.CharField(blank=True, max_length=150, null=True)),
                ('visitor_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'member'), name='uq_session_member')],
            },
        ),
    ]
